name: Generate ver.txt

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  jobs:
    generate-version:
      if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Generate ver.txt
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "$VERSION" > ver.txt

      - name: Commit ver.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ver.txt
          git commit -m "chore: update ver.txt" || echo "No changes"
          git push
